### ISSUE TITLE
Inference time correction

### ISSUE THREAD

**Issue by alsaleem00** [erentknn/yolov4-object-detection#1]
I would like to thank you for your effort to simply using opencv from python.
It did save me considerable time.

In py file (yolo_image.py) line 99-100,
it indicates inference time in ms, while it should be in seconds.

I got (0.51 sec) in CPU mode as my opencv was not built with GPU.  It falls back to CPU automatically.

**Comment by erentknn** [comment]
Thanks for this, fixed in 05da090fb014682ff7006ebe5f2ae3d21635abd7
