### ISSUE TITLE
layer[i[0]] -> layer[i]

### ISSUE THREAD

**Issue by Roger-Lo2000** [erentknn/yolov4-object-detection#2]
I had a bug in line 56 in yolo_image.py 
layer = [layer[i[0] - 1] for i in net.getUnconnectedOutLayers()]  
and line 75 in yolo_video.py 
layer = [layer[i[0] - 1] for i in net.getUnconnectedOutLayers()]

I found that the problem is i[0], change  i[0]->i  will work! 
Is that opencv version Problem or anythiing else?

**Comment by erentknn** [comment]
How can I reproduce this? With which config you encountered to this? It's hard to say something without the specifics.

**Comment by Roger-Lo2000** [comment]
![error message](https://user-images.githubusercontent.com/79558403/155955883-df587c5b-9164-40d7-8f50-4a4f64565d54.PNG)
This is what I get when I run the code without changing anything.
Sorry for the late responese.
Enviroment:
    python=3.6,opencv-python=4.5,numpy=1.19

**Comment by hb0313** [comment]
Issue is reproducible on colab notebook.
Also, you might wanna add assertion:

image = cv2.imread(imgpath)
assert not isinstance(image,type(None)), 'image not found'

**Comment by erentknn** [comment]
fixed with [12391b4](https://github.com/erentknn/yolov4-object-detection/commit/12391b4b7c06e8773fb5b3c335babdbd901a57a7)
